# 版本1
version: "1"

# 服务
services:
  
  # 应用
  applications:
    image: tianon/true
    volumes:
        - "${APPLICATION}:/var/www"
  
  # 工作空间
  workspace:
    build:
      context: ./workspace
      args: null
      dockerfile: "Dockerfile-{$PHP_VERSION}"
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
      tty: true
      networks:
        - frontend
        - backend
  
  # php解析器
  php-fpm:
    build:
      context: ./php-fpm
      args: null
      volumes_from:
        - applications
      volumes:
        - "./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini"
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - "PHP_IDE_CONFIG=${PHP_IDE_CONFIG}"
      networks:
        - backend
  
  # nginx构建
  nginx:
    build:
      context: ./nginx
    volumes_from:
      - applications
    volumes:
      - "${NGINX_HOST_LOG_PATH}:/var/log/nginx"
      - "${NGINX_SITES_PATH}:/etc/nginx/sites-available"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
  
  # mysql构建
  mysql:
    build:
      context: ./mysql
      args:
        - "MYSQL_VERSION=${MYSQL_VERSION}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${WORKSPACE_TIMEZONE}"
    volumes:
      - "${DATA_SAVE_PATH}/mysql:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
  
  # mongodb构建
  mongo:
    build: ./mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - "${DATA_SAVE_PATH}/mongo:/data/db"
    networks:
      - backend
  
  # redis构建
  redis:
    build: ./redis
    volumes:
      - "${DATA_SAVE_PATH}/redis:/data"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  
  # memcached构建
  memcached:
    build: ./memcached
    volumes:
      - "${DATA_SAVE_PATH}/memcached:/var/lib/memcached"
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    depends_on:
      - php-fpm
    networks:
      - backend
  
  # phpmyadmin构建
  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - "MYSQL_USER=${PMA_USER}"
      - "MYSQL_PASSWORD=${PMA_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend

# 网络
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# 数据卷
volumes:
  mysql:
    driver: local_php
  memcached:
    driver: local_php
  redis:
    driver: local_php
  mongo:
    driver: local_php
  phpmyadmin:
    driver: local_php

# 参考之https://github.com/laradock/laradock